spring:
  application:
    name: provider01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gen_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456

  rabbitmq: #对于rabbitMQ的支持
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # ------- 消息确认配置项 --------
    # 确认消息已发送到交换机
    publisher-confirms: true
    # 确认消息已发送队列
    publisher-returns: true

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 0

#\u670D\u52A1\u7AEF\u53E3
server:
  port: 8771

# \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8672/eureka/  #\u6CE8\u518C\u5730\u5740
  instance:
    prefer-ip-address: true

#控制台打印sql日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml   #指定mapper.xml位置

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

