server:
  port: 8772
spring:
  application:
    name: comsumer
  main:
    allow-bean-definition-overriding: true #允许存在多个Feign调用相同Service的接口
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gen_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8763.com:8763/eureka/  #服务注册地址
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
#  由于Ribbon是懒加载的，在首次请求时，才会开始初始化相关类，第一次调用时间会长一些
#  该配置是让Hystrix的超时时间改为5秒,超过这个时间没有调到，就熔断
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
#  从Dalston开始，Ribbon支持配置eager load实现在启动时就初始化Ribbon相关类。
ribbon:
  eager-load:
    enabled: true
    clients: provider01


#服务名称  ribbon 时用到
provider: provider01

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置随机
provider01:   # 表示作用哪个服务 现在provider01 还只有一个
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

